import { memo, useState } from 'react';
import {
  MapPin,
  Calendar,
  Wallet,
  Heart,
  ChevronDown,
  Download,
  CheckSquare,
  Square,
  Lightbulb,
  AlertCircle,
  Loader2,
} from 'lucide-react';

/**
 * @param {{ day: object, expanded: boolean, onToggle: () => void }} props
 */
const TripDayAccordion = memo(function TripDayAccordion({ day, expanded, onToggle }) {
  return (
    <div className="rounded-lg border border-white/5 bg-navy/60 overflow-hidden">
      <button
        type="button"
        onClick={onToggle}
        className="w-full flex items-center justify-between px-3 py-2.5 text-left
                   hover:bg-white/5 transition-colors focus:outline-none focus:ring-2 focus:ring-amber/20"
        aria-expanded={expanded}
        aria-label={`Day ${day.day}: ${day.location}`}
      >
        <span className="text-sm font-medium text-cream">
          Day {day.day}
          <span className="text-cream/50 font-normal ml-1.5">{day.location}</span>
        </span>
        <ChevronDown
          className={`w-4 h-4 text-amber/60 transition-transform duration-200 ${
            expanded ? 'rotate-180' : ''
          }`}
        />
      </button>

      {expanded && (
        <div className="px-3 pb-3 space-y-2 border-t border-white/5 pt-2">
          {day.theme && <p className="text-xs text-amber/70 italic">{day.theme}</p>}
          {day.morning && <TimeSlot label="Morning" activity={day.morning} whyToday={day.morningWhy} />}
          {day.afternoon && <TimeSlot label="Afternoon" activity={day.afternoon} whyToday={day.afternoonWhy} />}
          {day.evening && <TimeSlot label="Evening" activity={day.evening} whyToday={day.eveningWhy} />}
        </div>
      )}
    </div>
  );
});

/**
 * Trip plan view — itinerary, checklist, insider tips, and download.
 */
export default function TripSummaryPanel({
  tripData,
  checklistState,
  onToggleChecklist,
  isStreamingPlan = false,
  error = null,
  onRetry,
}) {
  const [expandedDays, setExpandedDays] = useState({ 1: true });

  const { destination, dates, budget, interests, itinerary, checklist, tips } = tripData;
  const showInitialSpinner = isStreamingPlan && !(itinerary?.length);
  const showGeneratingBadge = isStreamingPlan && (itinerary?.length ?? 0) > 0;
  const hasContent =
    destination || dates || budget || interests?.length || itinerary?.length ||
    checklist?.packing?.length || checklist?.booking?.length || tips;

  function toggleDay(day) {
    setExpandedDays((prev) => ({ ...prev, [day]: !prev[day] }));
  }

  function downloadSummary() {
    const lines = [
      '═══════════════════════════════════════',
      '       VOYAGER AI — TRIP SUMMARY',
      '═══════════════════════════════════════',
      '',
    ];

    if (destination) lines.push(`📍 Destination: ${destination}`);
    if (dates) lines.push(`📅 Dates: ${dates}`);
    if (budget) lines.push(`💰 Budget: ${budget}`);
    if (interests?.length) lines.push(`🗺️ Interests: ${interests.join(', ')}`);
    lines.push('');

    if (itinerary?.length) {
      lines.push('── ITINERARY ──', '');
      itinerary.forEach((day) => {
        lines.push(`DAY ${day.day} | ${day.location}: ${day.theme}`);
        if (day.morning) lines.push(`  Morning:   ${day.morning}${day.morningWhy ? ` Why today: ${day.morningWhy}` : ''}`);
        if (day.afternoon) lines.push(`  Afternoon: ${day.afternoon}${day.afternoonWhy ? ` Why today: ${day.afternoonWhy}` : ''}`);
        if (day.evening) lines.push(`  Evening:   ${day.evening}${day.eveningWhy ? ` Why today: ${day.eveningWhy}` : ''}`);
        lines.push('');
      });
    }

    if (checklist?.packing?.length || checklist?.booking?.length) {
      lines.push('── CHECKLIST ──', '');
      if (checklist.packing?.length) {
        lines.push('Packing:');
        checklist.packing.forEach((item) => {
          const checked = checklistState[`packing-${item}`];
          lines.push(`  ${checked ? '☑' : '☐'} ${item}`);
        });
        lines.push('');
      }
      if (checklist.booking?.length) {
        lines.push('Booking:');
        checklist.booking.forEach((item) => {
          const checked = checklistState[`booking-${item}`];
          lines.push(`  ${checked ? '☑' : '☐'} ${item}`);
        });
        lines.push('');
      }
    }

    if (tips) {
      lines.push('── INSIDER TIPS ──', '', tips, '');
    }

    lines.push('', 'Generated by Voyager AI ✈️');

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `voyager-trip-${destination || 'plan'}.txt`.replace(/\s+/g, '-').toLowerCase();
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <aside
      className="flex flex-col h-full bg-navy-light/80 backdrop-blur-md border-amber/20"
      aria-label="Trip summary"
    >
      <div className="px-5 py-4 border-b border-amber/15">
        <div className="flex items-center justify-between gap-2">
          <h2 className="font-display text-lg font-semibold text-amber">
            Your Trip Plan
          </h2>
          {showGeneratingBadge && (
            <span className="text-xs text-amber/70 bg-amber/10 border border-amber/20 px-2 py-0.5 rounded-full">
              Generating…
            </span>
          )}
        </div>
        <p className="text-xs text-cream/40 mt-0.5">
          {showInitialSpinner ? 'Building your itinerary…' : 'Everything in one place'}
        </p>
      </div>

      <div className="flex-1 overflow-y-auto px-5 py-4 space-y-5">
        {showInitialSpinner && (
          <div className="flex flex-col items-center justify-center py-16 gap-4 text-center">
            <Loader2 className="w-10 h-10 text-amber animate-spin" aria-hidden="true" />
            <p className="text-sm text-cream/60">Building your day-by-day itinerary…</p>
          </div>
        )}

        {error && (
          <div
            className="flex items-start gap-3 p-4 rounded-xl bg-red-900/20 border border-red-500/30"
            role="alert"
          >
            <AlertCircle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" />
            <div className="flex-1 min-w-0">
              <p className="text-sm text-red-300">{error}</p>
              {onRetry && !error.includes('insufficient balance') && !error.includes('Invalid API key') && (
                <button
                  type="button"
                  onClick={onRetry}
                  className="mt-2 px-3 py-1.5 text-xs font-medium rounded-lg bg-red-500/20 text-red-300
                             hover:bg-red-500/30 transition-colors focus:outline-none focus:ring-2 focus:ring-red-400/40"
                >
                  Try again
                </button>
              )}
            </div>
          </div>
        )}

        {!showInitialSpinner && !hasContent && (
          <p className="text-sm text-cream/30 text-center py-8">
            Your plan will appear here once generation finishes…
          </p>
        )}

        {destination && <SummaryField icon={MapPin} label="Destination" value={destination} />}
        {dates && <SummaryField icon={Calendar} label="Dates & Duration" value={dates} />}
        {budget && <SummaryField icon={Wallet} label="Budget" value={budget} />}
        {interests?.length > 0 && (
          <SummaryField icon={Heart} label="Interests" value={interests.join(', ')} />
        )}

        {itinerary?.length > 0 && (
          <div>
            <h3 className="text-xs font-semibold uppercase tracking-wider text-teal mb-3">
              Day-by-Day Itinerary
            </h3>
            <div className="space-y-2">
              {itinerary.map((day) => (
                <TripDayAccordion
                  key={day.day}
                  day={day}
                  expanded={!!expandedDays[day.day]}
                  onToggle={() => toggleDay(day.day)}
                />
              ))}
            </div>
          </div>
        )}

        {(checklist?.packing?.length > 0 || checklist?.booking?.length > 0) && (
          <div>
            <h3 className="text-xs font-semibold uppercase tracking-wider text-teal mb-3">
              Packing & Booking
            </h3>
            {checklist.packing?.length > 0 && (
              <ChecklistGroup
                title="Packing"
                items={checklist.packing}
                prefix="packing"
                checklistState={checklistState}
                onToggle={onToggleChecklist}
              />
            )}
            {checklist.booking?.length > 0 && (
              <ChecklistGroup
                title="Booking"
                items={checklist.booking}
                prefix="booking"
                checklistState={checklistState}
                onToggle={onToggleChecklist}
              />
            )}
          </div>
        )}

        {tips && (
          <div>
            <h3 className="text-xs font-semibold uppercase tracking-wider text-teal mb-3 flex items-center gap-1.5">
              <Lightbulb className="w-3.5 h-3.5" aria-hidden="true" />
              Insider Tips
            </h3>
            <div className="text-sm text-cream/80 leading-relaxed whitespace-pre-wrap">{tips}</div>
          </div>
        )}
      </div>

      {hasContent && !isStreamingPlan && (
        <div className="px-5 py-4 border-t border-amber/15">
          <button
            type="button"
            onClick={downloadSummary}
            aria-label="Download trip summary as text file"
            className="w-full flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl
                       bg-amber/15 border border-amber/30 text-amber text-sm font-medium
                       hover:bg-amber/25 transition-colors focus:outline-none focus:ring-2 focus:ring-amber/40"
          >
            <Download className="w-4 h-4" />
            Download Summary
          </button>
        </div>
      )}
    </aside>
  );
}

function SummaryField({ icon: Icon, label, value }) {
  return (
    <div className="flex gap-3">
      <Icon className="w-4 h-4 text-amber/70 mt-0.5 flex-shrink-0" aria-hidden="true" />
      <div>
        <p className="text-xs text-cream/40 uppercase tracking-wider">{label}</p>
        <p className="text-sm text-cream mt-0.5">{value}</p>
      </div>
    </div>
  );
}

function TimeSlot({ label, activity, whyToday }) {
  return (
    <div className="text-xs mb-2 last:mb-0">
      <p>
        <span className="text-teal/70 font-medium">{label}:</span>{' '}
        <span className="text-cream/70">{activity}</span>
      </p>
      {whyToday && (
        <p className="mt-1 pl-3 border-l border-amber/25 text-cream/50 italic leading-snug">
          Why today:
          {' '}
          {whyToday}
        </p>
      )}
    </div>
  );
}

function ChecklistGroup({ title, items, prefix, checklistState, onToggle }) {
  return (
    <div className="mb-3">
      <p className="text-xs text-cream/50 mb-1.5 font-medium">{title}</p>
      <ul className="space-y-1">
        {items.map((item) => {
          const key = `${prefix}-${item}`;
          const checked = checklistState[key];
          return (
            <li key={key}>
              <button
                type="button"
                onClick={() => onToggle(key)}
                aria-label={`${checked ? 'Uncheck' : 'Check'} ${item}`}
                className="flex items-start gap-2 w-full text-left text-xs py-1 rounded
                           hover:bg-white/5 transition-colors focus:outline-none focus:ring-2 focus:ring-amber/20"
              >
                {checked ? (
                  <CheckSquare className="w-3.5 h-3.5 text-teal mt-0.5 flex-shrink-0" />
                ) : (
                  <Square className="w-3.5 h-3.5 text-cream/30 mt-0.5 flex-shrink-0" />
                )}
                <span className={checked ? 'text-cream/40 line-through' : 'text-cream/80'}>{item}</span>
              </button>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
