/** Maps each UK destination id to its primary public-transport hub. */
export const DESTINATION_HUBS = {
  london: 'london',
  manchester: 'manchester',
  liverpool: 'liverpool',
  birmingham: 'birmingham',
  bristol: 'bristol',
  newcastle: 'newcastle',
  leeds: 'leeds',
  sheffield: 'sheffield',
  nottingham: 'nottingham',
  cambridge: 'cambridge',
  oxford: 'oxford',
  'brighton-coast': 'brighton',
  'bath-somerset': 'bath',
  york: 'york',
  canterbury: 'canterbury',
  chester: 'chester',
  durham: 'durham',
  lincoln: 'lincoln',
  'stratford-upon-avon': 'stratford',
  blackpool: 'blackpool',
  bournemouth: 'bournemouth',
  'lake-district': 'windermere',
  'peak-district': 'buxton',
  cornwall: 'penzance',
  devon: 'exeter',
  dorset: 'weymouth',
  cotswolds: 'moreton',
  'yorkshire-dales': 'skipton',
  'north-york-moors': 'whitby',
  'norfolk-broads': 'norwich',
  'new-forest': 'southampton',
  'jurassic-coast': 'weymouth',
  'kent-downs': 'canterbury',
  'winchester-hampshire': 'winchester',
  edinburgh: 'edinburgh',
  glasgow: 'glasgow',
  'scottish-highlands': 'inverness',
  aberdeen: 'aberdeen',
  inverness: 'inverness',
  stirling: 'stirling',
  'loch-lomond': 'balloch',
  'isle-of-skye': 'kyle',
  orkney: 'kirkwall',
  'st-andrews': 'leuchars',
  'scottish-borders': 'berwick',
  cardiff: 'cardiff',
  snowdonia: 'bangor',
  pembrokeshire: 'haverfordwest',
  'brecon-beacons': 'abergavenny',
  tenby: 'tenby',
  'swansea-gower': 'swansea',
  anglesey: 'bangor',
  belfast: 'belfast',
  'causeway-coast': 'belfast',
  derry: 'derry',
  'mourne-mountains': 'newcastle-ni',
  'isle-of-wight': 'ryde',
};

/** Home city id maps to same hub id for routing. */
export const HOME_HUBS = {
  london: 'london',
  manchester: 'manchester',
  birmingham: 'birmingham',
  leeds: 'leeds',
  bristol: 'bristol',
  liverpool: 'liverpool',
  newcastle: 'newcastle',
  sheffield: 'sheffield',
  edinburgh: 'edinburgh',
  glasgow: 'glasgow',
  cardiff: 'cardiff',
  belfast: 'belfast',
};

export const NI_HUBS = new Set(['belfast', 'derry', 'newcastle-ni']);
export const GB_HUBS = new Set(Object.values(DESTINATION_HUBS).filter((h) => !NI_HUBS.has(h)));
