/**
 * Curated UK rail / flight legs between travel hubs.
 * Times = typical fastest service; prices = advance single from (Jun 2026 typical).
 * Sources: National Rail timetables, operator sites, Trainline advance fares.
 *
 * @typedef {{ minutes: number, priceFrom: number, operator: string, detail?: string }} TravelLeg
 */

/** @type {Record<string, TravelLeg>} key: fromHub|toHub (sorted alphabetically in lookup) */
export const DIRECT_LEGS = {
  'aberdeen|edinburgh': { minutes: 135, priceFrom: 18, operator: 'ScotRail', detail: 'Direct' },
  'aberdeen|glasgow': { minutes: 150, priceFrom: 22, operator: 'ScotRail / LNER', detail: 'Via Edinburgh' },
  'aberdeen|inverness': { minutes: 135, priceFrom: 20, operator: 'ScotRail', detail: 'Direct' },
  'bangor|chester': { minutes: 95, priceFrom: 16, operator: 'Transport for Wales', detail: 'Direct' },
  'bangor|liverpool': { minutes: 110, priceFrom: 18, operator: 'Transport for Wales / Avanti', detail: '1 change' },
  'bangor|manchester': { minutes: 120, priceFrom: 20, operator: 'Transport for Wales / Avanti', detail: '1 change' },
  'bath|bristol': { minutes: 18, priceFrom: 6, operator: 'GWR', detail: 'Direct' },
  'bath|london': { minutes: 82, priceFrom: 18, operator: 'GWR', detail: 'London Paddington' },
  'berwick|edinburgh': { minutes: 45, priceFrom: 10, operator: 'LNER / CrossCountry', detail: 'Direct' },
  'berwick|newcastle': { minutes: 38, priceFrom: 9, operator: 'LNER', detail: 'Direct' },
  'birmingham|bristol': { minutes: 78, priceFrom: 16, operator: 'CrossCountry', detail: 'Direct' },
  'birmingham|cardiff': { minutes: 125, priceFrom: 18, operator: 'CrossCountry / GWR', detail: '1 change' },
  'birmingham|chester': { minutes: 62, priceFrom: 12, operator: 'Avanti / Transport for Wales', detail: 'Direct' },
  'birmingham|edinburgh': { minutes: 240, priceFrom: 32, operator: 'Avanti / LNER', detail: '1 change' },
  'birmingham|glasgow': { minutes: 255, priceFrom: 35, operator: 'Avanti / Avanti', detail: '1 change' },
  'birmingham|leeds': { minutes: 118, priceFrom: 16, operator: 'CrossCountry', detail: 'Direct' },
  'birmingham|liverpool': { minutes: 98, priceFrom: 14, operator: 'Avanti / West Midlands', detail: '1 change' },
  'birmingham|london': { minutes: 83, priceFrom: 14, operator: 'Avanti West Coast', detail: 'London Euston' },
  'birmingham|manchester': { minutes: 88, priceFrom: 12, operator: 'Avanti / CrossCountry', detail: 'Direct' },
  'birmingham|newcastle': { minutes: 175, priceFrom: 28, operator: 'CrossCountry', detail: 'Direct' },
  'birmingham|nottingham': { minutes: 72, priceFrom: 10, operator: 'CrossCountry', detail: 'Direct' },
  'birmingham|sheffield': { minutes: 62, priceFrom: 10, operator: 'CrossCountry', detail: 'Direct' },
  'birmingham|york': { minutes: 130, priceFrom: 18, operator: 'CrossCountry', detail: 'Direct' },
  'blackpool|liverpool': { minutes: 75, priceFrom: 12, operator: 'Northern', detail: '1 change' },
  'blackpool|manchester': { minutes: 68, priceFrom: 11, operator: 'Northern', detail: 'Direct' },
  'bournemouth|london': { minutes: 118, priceFrom: 16, operator: 'South Western Railway', detail: 'London Waterloo' },
  'bournemouth|southampton': { minutes: 32, priceFrom: 8, operator: 'South Western Railway', detail: 'Direct' },
  'brighton|london': { minutes: 58, priceFrom: 10, operator: 'Southern / Thameslink', detail: 'London Victoria / St Pancras' },
  'bristol|cardiff': { minutes: 42, priceFrom: 8, operator: 'GWR / Transport for Wales', detail: 'Direct' },
  'bristol|london': { minutes: 98, priceFrom: 20, operator: 'GWR', detail: 'London Paddington' },
  'bristol|plymouth': { minutes: 105, priceFrom: 18, operator: 'GWR', detail: 'Direct' },
  'bristol|exeter': { minutes: 68, priceFrom: 14, operator: 'GWR', detail: 'Direct' },
  'buxton|manchester': { minutes: 58, priceFrom: 9, operator: 'Northern', detail: 'Direct' },
  'buxton|sheffield': { minutes: 48, priceFrom: 8, operator: 'Northern', detail: 'Direct' },
  'cambridge|london': { minutes: 50, priceFrom: 10, operator: 'Great Northern / Thameslink', detail: 'London King\'s Cross' },
  'canterbury|london': { minutes: 62, priceFrom: 12, operator: 'Southeastern', detail: 'London St Pancras' },
  'cardiff|bristol': { minutes: 42, priceFrom: 8, operator: 'GWR / Transport for Wales', detail: 'Direct' },
  'cardiff|london': { minutes: 114, priceFrom: 22, operator: 'GWR', detail: 'London Paddington' },
  'cardiff|swansea': { minutes: 52, priceFrom: 8, operator: 'GWR / Transport for Wales', detail: 'Direct' },
  'chester|liverpool': { minutes: 42, priceFrom: 8, operator: 'Merseyrail / Transport for Wales', detail: 'Direct' },
  'chester|manchester': { minutes: 58, priceFrom: 10, operator: 'Transport for Wales / Northern', detail: 'Direct' },
  'derry|belfast': { minutes: 125, priceFrom: 12, operator: 'Translink', detail: 'Train + bus via Coleraine' },
  'durham|edinburgh': { minutes: 105, priceFrom: 16, operator: 'LNER / CrossCountry', detail: '1 change' },
  'durham|newcastle': { minutes: 12, priceFrom: 4, operator: 'LNER / Northern', detail: 'Direct' },
  'durham|york': { minutes: 38, priceFrom: 8, operator: 'LNER / CrossCountry', detail: 'Direct' },
  'edinburgh|glasgow': { minutes: 50, priceFrom: 8, operator: 'ScotRail / LNER', detail: 'Direct' },
  'edinburgh|inverness': { minutes: 210, priceFrom: 28, operator: 'ScotRail / LNER', detail: 'Direct' },
  'edinburgh|leuchars': { minutes: 55, priceFrom: 10, operator: 'ScotRail / LNER', detail: 'Direct' },
  'edinburgh|stirling': { minutes: 48, priceFrom: 9, operator: 'ScotRail / LNER', detail: 'Direct' },
  'exeter|london': { minutes: 128, priceFrom: 22, operator: 'GWR', detail: 'London Paddington' },
  'exeter|plymouth': { minutes: 52, priceFrom: 10, operator: 'GWR', detail: 'Direct' },
  'glasgow|inverness': { minutes: 195, priceFrom: 26, operator: 'ScotRail', detail: 'Direct' },
  'glasgow|kyle': { minutes: 330, priceFrom: 38, operator: 'ScotRail', detail: 'Via Inverness' },
  'glasgow|balloch': { minutes: 50, priceFrom: 8, operator: 'ScotRail', detail: 'Direct' },
  'haverfordwest|cardiff': { minutes: 145, priceFrom: 18, operator: 'Transport for Wales', detail: 'Direct' },
  'inverness|kyle': { minutes: 150, priceFrom: 22, operator: 'ScotRail', detail: 'Direct' },
  'leeds|edinburgh': { minutes: 165, priceFrom: 22, operator: 'LNER / CrossCountry', detail: 'Direct' },
  'leeds|london': { minutes: 134, priceFrom: 18, operator: 'LNER', detail: 'London King\'s Cross' },
  'leeds|manchester': { minutes: 52, priceFrom: 8, operator: 'TransPennine Express / Northern', detail: 'Direct' },
  'leeds|newcastle': { minutes: 88, priceFrom: 14, operator: 'LNER / CrossCountry', detail: 'Direct' },
  'leeds|sheffield': { minutes: 38, priceFrom: 6, operator: 'Northern / CrossCountry', detail: 'Direct' },
  'leeds|york': { minutes: 22, priceFrom: 5, operator: 'LNER / Northern', detail: 'Direct' },
  'leuchars|edinburgh': { minutes: 55, priceFrom: 10, operator: 'ScotRail / LNER', detail: 'Direct' },
  'lincoln|london': { minutes: 125, priceFrom: 16, operator: 'LNER / EMR', detail: '1 change' },
  'lincoln|nottingham': { minutes: 42, priceFrom: 8, operator: 'EMR', detail: 'Direct' },
  'liverpool|london': { minutes: 134, priceFrom: 22, operator: 'Avanti West Coast', detail: 'London Euston' },
  'liverpool|manchester': { minutes: 35, priceFrom: 6, operator: 'Northern / TransPennine', detail: 'Direct' },
  'london|manchester': { minutes: 127, priceFrom: 22, operator: 'Avanti West Coast', detail: 'London Euston' },
  'london|birmingham': { minutes: 83, priceFrom: 14, operator: 'Avanti West Coast', detail: 'London Euston' },
  'london|leeds': { minutes: 134, priceFrom: 18, operator: 'LNER', detail: 'London King\'s Cross' },
  'london|bristol': { minutes: 98, priceFrom: 20, operator: 'GWR', detail: 'London Paddington' },
  'london|liverpool': { minutes: 134, priceFrom: 22, operator: 'Avanti West Coast', detail: 'London Euston' },
  'london|newcastle': { minutes: 172, priceFrom: 24, operator: 'LNER', detail: 'London King\'s Cross' },
  'london|edinburgh': { minutes: 258, priceFrom: 28, operator: 'LNER', detail: 'London King\'s Cross' },
  'london|glasgow': { minutes: 270, priceFrom: 32, operator: 'Avanti West Coast', detail: 'London Euston' },
  'london|cardiff': { minutes: 114, priceFrom: 22, operator: 'GWR', detail: 'London Paddington' },
  'london|sheffield': { minutes: 124, priceFrom: 16, operator: 'EMR / LNER', detail: 'London St Pancras' },
  'london|nottingham': { minutes: 105, priceFrom: 14, operator: 'EMR', detail: 'London St Pancras' },
  'london|norwich': { minutes: 110, priceFrom: 14, operator: 'Greater Anglia', detail: 'London Liverpool Street' },
  'london|oxford': { minutes: 56, priceFrom: 12, operator: 'GWR / Chiltern', detail: 'London Paddington / Marylebone' },
  'london|cambridge': { minutes: 50, priceFrom: 10, operator: 'Great Northern', detail: 'London King\'s Cross' },
  'london|brighton': { minutes: 58, priceFrom: 10, operator: 'Southern', detail: 'London Victoria' },
  'london|bath': { minutes: 82, priceFrom: 18, operator: 'GWR', detail: 'London Paddington' },
  'london|york': { minutes: 118, priceFrom: 18, operator: 'LNER', detail: 'London King\'s Cross' },
  'london|exeter': { minutes: 128, priceFrom: 22, operator: 'GWR', detail: 'London Paddington' },
  'london|penzance': { minutes: 305, priceFrom: 38, operator: 'GWR', detail: 'London Paddington' },
  'london|oxenholme': { minutes: 176, priceFrom: 28, operator: 'Avanti West Coast', detail: 'London Euston · + branch to Windermere' },
  'london|windermere': { minutes: 210, priceFrom: 32, operator: 'Avanti + Northern', detail: 'Change Oxenholme' },
  'london|moreton': { minutes: 95, priceFrom: 18, operator: 'GWR', detail: 'London Paddington' },
  'london|weymouth': { minutes: 145, priceFrom: 22, operator: 'South Western Railway', detail: 'London Waterloo' },
  'london|bournemouth': { minutes: 118, priceFrom: 16, operator: 'South Western Railway', detail: 'London Waterloo' },
  'london|southampton': { minutes: 78, priceFrom: 14, operator: 'South Western Railway', detail: 'London Waterloo' },
  'london|blackpool': { minutes: 165, priceFrom: 24, operator: 'Avanti + Northern', detail: '1 change' },
  'london|skipton': { minutes: 155, priceFrom: 22, operator: 'LNER + Northern', detail: '1 change' },
  'london|tenby': { minutes: 280, priceFrom: 35, operator: 'GWR', detail: 'London Paddington' },
  'london|abergavenny': { minutes: 150, priceFrom: 24, operator: 'GWR', detail: 'London Paddington' },
  'london|haverfordwest': { minutes: 295, priceFrom: 38, operator: 'GWR', detail: 'London Paddington' },
  'manchester|edinburgh': { minutes: 195, priceFrom: 26, operator: 'TransPennine / Avanti', detail: '1 change' },
  'manchester|glasgow': { minutes: 210, priceFrom: 28, operator: 'TransPennine / Avanti', detail: '1 change' },
  'manchester|leeds': { minutes: 52, priceFrom: 8, operator: 'TransPennine / Northern', detail: 'Direct' },
  'manchester|liverpool': { minutes: 35, priceFrom: 6, operator: 'Northern / TransPennine', detail: 'Direct' },
  'manchester|london': { minutes: 127, priceFrom: 22, operator: 'Avanti West Coast', detail: 'London Euston' },
  'manchester|newcastle': { minutes: 145, priceFrom: 20, operator: 'TransPennine / CrossCountry', detail: 'Direct' },
  'manchester|sheffield': { minutes: 48, priceFrom: 8, operator: 'TransPennine / Northern', detail: 'Direct' },
  'manchester|york': { minutes: 88, priceFrom: 14, operator: 'TransPennine / Northern', detail: 'Direct' },
  'manchester|buxton': { minutes: 58, priceFrom: 9, operator: 'Northern', detail: 'Direct' },
  'moreton|london': { minutes: 95, priceFrom: 18, operator: 'GWR', detail: 'London Paddington' },
  'newcastle|edinburgh': { minutes: 90, priceFrom: 14, operator: 'LNER / CrossCountry', detail: 'Direct' },
  'newcastle|london': { minutes: 172, priceFrom: 24, operator: 'LNER', detail: 'London King\'s Cross' },
  'newcastle|york': { minutes: 55, priceFrom: 10, operator: 'LNER', detail: 'Direct' },
  'norwich|london': { minutes: 110, priceFrom: 14, operator: 'Greater Anglia', detail: 'London Liverpool Street' },
  'nottingham|london': { minutes: 105, priceFrom: 14, operator: 'EMR', detail: 'London St Pancras' },
  'nottingham|sheffield': { minutes: 52, priceFrom: 8, operator: 'EMR / Northern', detail: 'Direct' },
  'oxford|london': { minutes: 56, priceFrom: 12, operator: 'GWR / Chiltern', detail: 'London terminals' },
  'penzance|plymouth': { minutes: 115, priceFrom: 14, operator: 'GWR', detail: 'Direct' },
  'plymouth|exeter': { minutes: 52, priceFrom: 10, operator: 'GWR', detail: 'Direct' },
  'plymouth|london': { minutes: 210, priceFrom: 32, operator: 'GWR', detail: 'London Paddington' },
  'ryde|southampton': { minutes: 75, priceFrom: 18, operator: 'Wightlink ferry + rail', detail: 'Foot passenger' },
  'sheffield|london': { minutes: 124, priceFrom: 16, operator: 'EMR / LNER', detail: 'London St Pancras' },
  'sheffield|manchester': { minutes: 48, priceFrom: 8, operator: 'TransPennine / Northern', detail: 'Direct' },
  'skipton|leeds': { minutes: 38, priceFrom: 7, operator: 'Northern', detail: 'Direct' },
  'southampton|london': { minutes: 78, priceFrom: 14, operator: 'South Western Railway', detail: 'London Waterloo' },
  'stirling|edinburgh': { minutes: 48, priceFrom: 9, operator: 'ScotRail / LNER', detail: 'Direct' },
  'stirling|glasgow': { minutes: 28, priceFrom: 6, operator: 'ScotRail', detail: 'Direct' },
  'stratford|london': { minutes: 95, priceFrom: 14, operator: 'Chiltern Railways', detail: 'London Marylebone' },
  'swansea|cardiff': { minutes: 52, priceFrom: 8, operator: 'GWR / Transport for Wales', detail: 'Direct' },
  'tenby|cardiff': { minutes: 165, priceFrom: 22, operator: 'GWR', detail: '1 change' },
  'weymouth|bournemouth': { minutes: 38, priceFrom: 8, operator: 'South Western Railway', detail: 'Direct' },
  'whitby|york': { minutes: 95, priceFrom: 12, operator: 'Northern bus 840', detail: 'Train to York + bus' },
  'windermere|oxenholme': { minutes: 18, priceFrom: 4, operator: 'Northern', detail: 'Branch line' },
  'winchester|london': { minutes: 58, priceFrom: 12, operator: 'South Western Railway', detail: 'London Waterloo' },
  'york|edinburgh': { minutes: 125, priceFrom: 18, operator: 'LNER', detail: 'Direct' },
  'york|london': { minutes: 118, priceFrom: 18, operator: 'LNER', detail: 'London King\'s Cross' },
  'york|leeds': { minutes: 22, priceFrom: 5, operator: 'LNER / Northern', detail: 'Direct' },
};

/** GB ↔ Northern Ireland flights (no rail tunnel). */
export const FLIGHT_LEGS = {
  'belfast|birmingham': { minutes: 75, priceFrom: 42, operator: 'easyJet / Aer Lingus', detail: 'Belfast City or International' },
  'belfast|bristol': { minutes: 70, priceFrom: 38, operator: 'easyJet', detail: 'Direct' },
  'belfast|cardiff': { minutes: 65, priceFrom: 40, operator: 'Aer Lingus', detail: 'Via Dublin or direct seasonal' },
  'belfast|edinburgh': { minutes: 55, priceFrom: 35, operator: 'easyJet / Loganair', detail: 'Direct' },
  'belfast|glasgow': { minutes: 50, priceFrom: 32, operator: 'easyJet', detail: 'Direct' },
  'belfast|leeds': { minutes: 70, priceFrom: 40, operator: 'easyJet', detail: 'Belfast–Leeds Bradford' },
  'belfast|liverpool': { minutes: 45, priceFrom: 28, operator: 'easyJet / Loganair', detail: 'Direct' },
  'belfast|london': { minutes: 75, priceFrom: 38, operator: 'British Airways / easyJet', detail: 'Gatwick, Heathrow, City, Stansted' },
  'belfast|manchester': { minutes: 50, priceFrom: 30, operator: 'easyJet / Aer Lingus', detail: 'Direct' },
  'belfast|newcastle': { minutes: 55, priceFrom: 32, operator: 'easyJet', detail: 'Direct' },
  'belfast|sheffield': { minutes: 75, priceFrom: 45, operator: 'Via Manchester', detail: '1 stop typical' },
};

/** Remote / island destinations — flight from nearest mainland airport. */
export const REMOTE_FLIGHTS = {
  kirkwall: { fromHub: 'edinburgh', minutes: 55, priceFrom: 55, operator: 'Loganair', detail: 'Edinburgh–Kirkwall' },
  kirkwall_aberdeen: { fromHub: 'aberdeen', minutes: 50, priceFrom: 50, operator: 'Loganair', detail: 'Aberdeen–Kirkwall' },
  kirkwall_inverness: { fromHub: 'inverness', minutes: 45, priceFrom: 48, operator: 'Loganair', detail: 'Inverness–Kirkwall' },
};
